### ISSUE TITLE
Not working on 1.3.4.4

### ISSUE THREAD

**Issue by dnish** [kadirahq/fast-render#176]
Hey,
Fast Render seems to be broken on my 1.3.4.4 application with Iron Router. The <code>Meteor.user()</code> object isn't available on the initial page load, everything worked fine before upgrading from 1.2 to 1.3.

**Comment by jschlieber** [comment]
I'm also having issues with the latest fast-render and Meteor 1.3.4.4 (same with [flow-router-ssr](https://github.com/kadirahq/flow-router/tree/ssr) and [react-router-ssr](https://github.com/thereactivestack/meteor-react-router-ssr)). Server side injected data isn't there at initial page load. Downgrading to fast-render@2.13.0 (kind of) solved those issues (as long as I don't make use of subs manager).

**Comment by VitalyChe** [comment]
It seems the FastRender injects the DDP messages correctly (when no connection yet) but the messages (came with html especially user data) never get processed and saved into collections due to `Accounts _autoLoginEnabled=true`. Enabled `autoLogin` is [the first to send message](https://github.com/meteor/meteor/blob/be986fd70926c9dd8eff6d8866205f236c8562c4/packages/accounts-base/localstorage_token.js#L117-L122) (login) [to the live data connection](https://github.com/meteor/meteor/blob/dce2b20ddbe45da48c37f26813fce8d0c72d8c88/packages/ddp-client/livedata_connection.js#L434) (token is taken from local storage) 
After that every message is [buffered](https://github.com/meteor/meteor/blob/dce2b20ddbe45da48c37f26813fce8d0c72d8c88/packages/ddp-client/livedata_connection.js#L1249) (that the FastRender injects) but is not processed due to `_waitingForQuiescence` (the first login message is there) [until the connection is established](https://github.com/meteor/meteor/blob/dce2b20ddbe45da48c37f26813fce8d0c72d8c88/packages/ddp-client/livedata_connection.js#L1261-L1262)

It happens when there is some delay before connection is establishe

**Comment by SachaG** [comment]
Has anybody found a fix for this? I can confirm this started happening with [1.3.3](https://github.com/meteor/meteor/blob/devel/History.md#v133) by the way.

**Comment by tmeasday** [comment]
Looks like it already has been fixed: https://github.com/kadirahq/fast-render/pull/167/files ?

**Comment by tmeasday** [comment]
You can turn off buffered DDP with `Meteor.connection.bufferedWritesMaxAge = 0` to work around this, I would guess.

**Comment by SachaG** [comment]
Note that it's actually `Meteor.connection._bufferedWritesMaxAge = 0` (on the client). Still doesn't fix the problem sadly :(

**Comment by tmeasday** [comment]
It was an issue with the fix for https://github.com/kadirahq/fast-render/pull/167 (https://github.com/kadirahq/fast-render/pull/167/files#r74189260)

I would suggest downgrading to 2.13.x and potentially using the bufferedWrites workaround (although your reproduction works for me without it).

**Comment by tmeasday** [comment]
(and the fix for this package is to revert the linked commit).

**Comment by arunoda** [comment]
Thanks @tmeasday I'll experiment with this today and do a release.
@SachaG could you verify that downgrading this solves your issue?

**Comment by SachaG** [comment]
Yes, I can confirm 2.13.0 doesn't have this problem.

**Comment by SachaG** [comment]
Hmm, that being said with 2.13.0 I seem to have reloading problems for *non*-logged-in users in Telescope. I'm not sure if it's a Telescope-specific issue though.

**Comment by tmeasday** [comment]
There could definitely be problems with 2.13 and 1.3.3 if you don't turn off DDP batching, I expect.

**Comment by gbhrdt** [comment]
Did you already look into this @arunoda ? :) this has pretty high severity for us right now.

**Comment by queso** [comment]
@arunoda: Any update on this? Kind of a blocker to launching a newer/faster SSR crater site....

**Comment by dnish** [comment]
Downgrading to 2.13.0 doesn't work very well (on some reloads everything works fine, on others I get a "expected document to change" without having the initial user data).

**Comment by dnish** [comment]
Maybe somone here can check the fix https://github.com/kadirahq/fast-render/pull/184 on his local project? In my case, everything is working fine now without problems.

**Comment by gbhrdt** [comment]
@dnish I just tested your fix, seems to be working for me, thanks!

**Comment by arunoda** [comment]
@dnish Hey thanks a lot for your fix. I just got it and did a release as v2.16.0. 
Try that. 

Thanks all for helping on this.
